# Site settings
title: Yossi Cohn
email: yossi.cohn@gmail.com
url: https://yossicohn.github.io
description: "This is me, here you can learn a bit about me"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Your Website

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/yossikuu
  - title: facebook
    url: http://facebook.com/yossicohn
  - title: stack-overflow
    url: https://stackoverflow.com/users/2692887/yossi-cohn
  - title: github
    url: https://github.com/yossicohn
  - title: linkedin
    url: https://www.linkedin.com/in/yossicohn/

# Build settings
markdown: kramdown
permalink: pretty
